### ISSUE TITLE
Use README for GitHub/GitLab links

### ISSUE THREAD

**Issue by LostBitset** [TetraTsunami/linklooker#10]
When using LinkLooker on a GitHub link, the AI usually just says weird stuff about how to search. 

![linklooker github weirdness png(1)](https://github.com/TetraTsunami/linklooker/assets/102832670/9621dc39-28ce-477b-8ca3-952342782823)

Given that it's already standard to explain your project in a README.md file, I think it would make a lot of sense to have a special case for links to GitHub repos, where the AI is asked to summarize only the README file. 

It would probably be a good idea to do the same thing with the GitLab, but the thing is that you can self-host GitLab under any URL. So instead of using the URL, we'll have to look for:

```html
<meta content="GitLab" property="og:site_name">
```

**Comment by the-snesler** [comment]
<img width="347" alt="firefox_wl6Gkn24dl" src="https://github.com/TetraTsunami/linklooker/assets/78718829/715e4d16-b5c8-454d-9c23-a2f5f39af107">

I've got it working with GitHub links. It should be simple enough to extend this foundation to GitLab and other types of sites (Twitter?), but I'm going to take a break for now.

**Comment by the-snesler** [comment]
Sorry this took so long :)
Newest version has [quite a few changes](https://github.com/TetraTsunami/linklooker/compare/1.1.4...1.1.6) and hopefully site-specific hacks like these should be much easier to implement in the future!
